const constants = {
	SET_OSC1_FREQ:   			'SET_OSC1_FREQ',
	SET_OSC1_SYNC:   			'SET_OSC1_SYNC',
	SET_OSC1_SHAPE:  			'SET_OSC1_SHAPE',
	SET_OSC1_PW:     			'SET_OSC1_PW',
	SET_OSC2_FREQ:   			'SET_OSC2_FREQ',
	SET_OSC2_FINE:   			'SET_OSC2_FINE',
	SET_OSC2_SHAPE:  			'SET_OSC2_SHAPE',
	SET_OSC2_PW:     			'SET_OSC2_PW',
	SET_OSC2_LOW_FREQ:		'SET_OSC2_LOW_FREQ',
	SET_OSC2_KEYBOARD: 		'SET_OSC2_KEYBOARD',
	SET_SLOP:							'SET_SLOP',
	SET_MIXER_OSC1:				'SET_MIXER_OSC1',
	SET_MIXER_OSC2:				'SET_MIXER_OSC2',
	SET_MIXER_SUB_OCTAVE:	'SET_MIXER_SUB_OCTAVE',
	SET_MIXER_NOISE:			'SET_MIXER_NOISE'
}

export default constants
